### ISSUE TITLE
マルチバイト文字を標準入力から渡すとpanicがおきる

### ISSUE THREAD

**Issue by jiro4989** [xztaityozx/t2p#1]
```bash
% echo あ | t2p
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/xztaityozx/t2p/palette.Palette.stringToRGBA(0xc0000c2800, 0x80, 0x80, 0xc0000183b8, 0x3, 0x7f2cc9de3008, 0x0, 0xc00009bbb4)
	/home/jiro4989/src/github.com/xztaityozx/t2p/palette/palette.go:62 +0x1c4
github.com/xztaityozx/t2p/palette.Palette.toImage(0xc0000c2800, 0x80, 0x80, 0xc0000183b8, 0x3, 0x3, 0x8, 0xc000010010, 0xc0000a4000)
	/home/jiro4989/src/github.com/xztaityozx/t2p/palette/palette.go:71 +0x74
github.com/xztaityozx/t2p/palette.Palette.Create(0xc0000c2800, 0x80, 0x80, 0x3, 0x1, 0xc000012750, 0x1, 0x1, 0x1)
	/home/jiro4989/src/github.com/xztaityozx/t2p/palette/palette.go:90 +0x255
github.com/xztaityozx/t2p/cmd.glob..func1(0x7a0f40, 0x7c11c0, 0x0, 0x0)
	/home/jiro4989/src/github.com/xztaityozx/t2p/cmd/root.go:69 +0x2c2
github.com/spf13/cobra.(*Command).execute(0x7a0f40, 0xc000012270, 0x0, 0x0, 0x7a0f40, 0xc000012270)
	/home/jiro4989/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x7a0f40, 0x63, 0xc0000b0100, 0xc0000b0100)
	/home/jiro4989/src/github.com/spf13/cobra/command.go:850 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jiro4989/src/github.com/spf13/cobra/command.go:800
github.com/xztaityozx/t2p/cmd.Execute()
	/home/jiro4989/src/github.com/xztaityozx/t2p/cmd/root.go:81 +0x32
main.main()
```

ソースとしては以下の箇所で発生してるみたいでした

https://github.com/xztaityozx/t2p/blob/fc63ebb5b5d0dc581a4dc5dc17f60acb14739b5e/palette/palette.go#L58-L66

**Comment by xztaityozx** [comment]
長さが128のスライスに対してチェック無しでアクセスしてるのが原因みたいですね。文字列のチェックは一箇所にまとめる必要がありそうです

さてマルチバイト文字についてですが、2文字に置き換えるのが丸いかなと思います

- マルチバイトを１文字にする場合
```sh
$ owari kanban --giko |  sed -E 'y/　￣＿終制作・∧著作ＮＨＫﾟдﾟづΦ/abcdefghijklmnopqr/'|t2p -o out.png -s 100
```

![image](https://user-images.githubusercontent.com/15944290/56865638-4e28ec00-6a0b-11e9-8392-30f296b12af6.png)

ずれてしまいますが、

- 2文字にする場合
```sh
$ owari kanban --giko | sed -E 'y/　￣＿終制作・∧著作ＮＨＫﾟдﾟづΦ/abcdefghijklmnopqr/'|cat|sed 's/[a-r]/&&/g'|t2p -o out.png -s100
```
![image](https://user-images.githubusercontent.com/15944290/56865662-7b759a00-6a0b-11e9-8515-6ea91df483ab.png)

上の枠のズレはないようです。（下は崩れてます）

**Comment by xztaityozx** [comment]
@jiro4989 #4 をマージしました！とりあえずこれでこの問題はOKだと思います。ありがとうございます！
